apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/wp-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

