name: Build/deploy myapp

on:
  push:
    branches:
      - main
    paths:
      - 'conf/**'
      - 'k8s/**'
      - 'wordpress/**'
      - '.github/**'
      - 'Dockerfile'

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: kubectl

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Authenticate Docker with GAR
      run: |
        echo "Configuring Docker to authenticate with Google Artifact Registry"
        gcloud auth configure-docker "asia-northeast1-docker.pkg.dev"

    - name: Build Docker Image
      run: |
        docker build -t  "asia-northeast1-docker.pkg.dev/mysandbox-443010/myapp/myapp-image:${{ github.sha }}" .

    - name: Push Docker Image to GAR
      run: |
        docker push "asia-northeast1-docker.pkg.dev/mysandbox-443010/myapp/myapp-image:${{ github.sha }}"

    - name: Configure kubeconfig
      run: |
        gcloud container clusters get-credentials myapp-infra --zone asia-northeast1-a

    - name: Deploy to Kubernetes
      run: |
        sed -i "s|image: .*|image: asia-northeast1-docker.pkg.dev/mysandbox-443010/myapp/myapp-image:${{ github.sha }}|" k8s/myapp-deployment.yaml
        kubectl apply -f k8s/

